- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  tasks:
     - name: Create a k8s namespace
       k8s:
          name: jenkins
          api_version: v1
          kind: Namespace
          state: present
     - name: Add stable chart repo
       community.kubernetes.helm_repository:
          name: jenkinsci
          repo_url : "https://charts.jenkins.io"
     - name: Create a PV.
       k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: jenkins-pv
            namespace: jenkins
          spec:
            storageClassName: jenkins-pv
            accessModes:
            - ReadWriteOnce
            capacity:
              storage: 10Gi
            persistentVolumeReclaimPolicy: Retain
            hostPath:
              path: /data/jenkins-volume/
     - name: Create a SA
       k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: jenkins
            namespace: jenkins
     - name: Create a ClusterRole
       k8s:
        state: present
        definition:
          kind: ClusterRole
          metadata:
            annotations:
              rbac.authorization.kubernetes.io/autoupdate: "true"
            labels:
              kubernetes.io/bootstrapping: rbac-defaults
            name: jenkins
          rules:
          - apiGroups:
            - '*'
            resources:
            - statefulsets
            - services
            - replicationcontrollers
            - replicasets
            - podtemplates
            - podsecuritypolicies
            - pods
            - pods/log
            - pods/exec
            - podpreset
            - poddisruptionbudget
            - persistentvolumes
            - persistentvolumeclaims
            - jobs
            - endpoints
            - deployments
            - deployments/scale
            - daemonsets
            - cronjobs
            - configmaps
            - namespaces
            - events
            - secrets
            verbs:
            - create
            - get
            - watch
            - delete
            - list
            - patch
            - update
          - apiGroups:
            - ""
            resources:
            - nodes
            verbs:
            - get
            - list
            - watch
            - update
     - name: Create a ClusterRoleBinding
       k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            annotations:
              rbac.authorization.kubernetes.io/autoupdate: "true"
            labels:
              kubernetes.io/bootstrapping: rbac-defaults
            name: jenkins
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: jenkins
          subjects:
          - apiGroup: rbac.authorization.k8s.io
            kind: Group
            name: system:serviceaccounts:jenkins
     - name: Deploy Grafana chart using values files on target
       community.kubernetes.helm:
          name: jenkins
          chart_ref: jenkinsci/jenkins
          release_namespace: jenkins
          values_files:
            - ./jenkins-values.yaml
